DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Insert_TBLusuario`(IN `p_ID_ESTADO_USUARIO` INT, IN `p_ID_ROL` INT, IN `p_ID_CENTRO_REGIONAL` INT, IN `p_NOMBRE_USUARIO` VARCHAR(50), IN `p_DNI` VARCHAR(15), IN `p_CONTRASENA` VARCHAR(50), IN `p_CORREO_ELECTRONICO` VARCHAR(50), IN `p_FECHA_CONEXION_ULTIMA` DATE, IN `p_COD_PRIMER_INGRESO` VARCHAR(255), IN `p_FECHA_VENCIMIENTO` DATE, IN `p_INTENTOS` INT)
INSERT INTO `tbl_ms_usuario` (
        `ID_ESTADO_USUARIO`, 
        `ID_ROLL`, 
        `ID_CENTRO_REGIONAL`, 
        `NOMBRE_USUARIO`,
        `DNI`, 
        `CONTRASENA`, 
        `CORREO_ELECTRONICO`, 
        `FECHA_CONEXION_ULTIMA`, 
        `COD_PRIMER_INGRESO`, 
        `FECHA_VENCIMIENTO`,
        `INTENTOS`
    )
    VALUES (
        p_ID_ESTADO_USUARIO, 
        p_ID_ROL, 
        p_ID_CENTRO_REGIONAL, 
        p_NOMBRE_USUARIO,
        p_DNI,
        p_CONTRASENA, 
        p_CORREO_ELECTRONICO, 
        p_FECHA_CONEXION_ULTIMA, 
        p_COD_PRIMER_INGRESO, 
        p_FECHA_VENCIMIENTO,
        p_INTENTOS
    )$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLUsuarioEstado_id`(IN `p_id` INT)
SELECT ue.ID_ESTADO_USUARIO, ue.DESCRIPCION FROM tbl_ms_usuario_estado ue where ID_ESTADO_USUARIO = p_id$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLparametro`()
SELECT * FROM `tbl_ms_parametro`$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLparametro_id`(IN `p_id` INT)
SELECT * FROM `tbl_ms_parametro` WHERE id_parametro = p_id$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLusuario`()
SELECT 
        u.ID_USUARIO,
        u.NOMBRE_USUARIO,
        u.CONTRASENA,
        u.CORREO_ELECTRONICO,
        u.FECHA_CONEXION_ULTIMA,
        u.COD_PRIMER_INGRESO,
        u.FECHA_VENCIMIENTO,
        u.INTENTOS,
        u.DNI,
        ue.DESCRIPCION AS ESTADO_USUARIO,
        r.DESCRIPCION AS ROL_USUARIO
    FROM 
        TBL_MS_USUARIO u
    INNER JOIN TBL_MS_USUARIO_ESTADO ue ON u.ID_ESTADO_USUARIO = ue.ID_ESTADO_USUARIO
    INNER JOIN TBL_MS_ROL r ON u.ID_ROLL = r.ID_ROL$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLusuario_correo`(IN `p_correo` VARCHAR(50))
SELECT 
        u.ID_USUARIO,
        u.NOMBRE_USUARIO,
        u.CONTRASENA,
        u.CORREO_ELECTRONICO,
        u.FECHA_CONEXION_ULTIMA,
        u.COD_PRIMER_INGRESO,
        u.FECHA_VENCIMIENTO,
        u.INTENTOS,
        u.DNI,
        ue.DESCRIPCION AS ESTADO_USUARIO,
        r.DESCRIPCION AS ROL_USUARIO
    FROM 
        TBL_MS_USUARIO u
    INNER JOIN TBL_MS_USUARIO_ESTADO ue ON u.ID_ESTADO_USUARIO = ue.ID_ESTADO_USUARIO
    INNER JOIN TBL_MS_ROL r ON u.ID_ROLL = r.ID_ROL
    WHERE
    	u.CORREO_ELECTRONICO = p_correo$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLusuario_id`(IN `p_id` INT)
SELECT 
        u.ID_USUARIO,
        u.NOMBRE_USUARIO,
        u.CONTRASENA,
        u.CORREO_ELECTRONICO,
        u.FECHA_CONEXION_ULTIMA,
        u.COD_PRIMER_INGRESO,
        u.FECHA_VENCIMIENTO,
        u.INTENTOS,
        u.DNI,
        ue.DESCRIPCION AS ESTADO_USUARIO,
        r.DESCRIPCION AS ROL_USUARIO
    FROM 
        TBL_MS_USUARIO u
    INNER JOIN TBL_MS_USUARIO_ESTADO ue ON u.ID_ESTADO_USUARIO = ue.ID_ESTADO_USUARIO
    INNER JOIN TBL_MS_ROL r ON u.ID_ROLL = r.ID_ROL
    WHERE
    	u.ID_USUARIO = p_id$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Select_TBLusuario_tkn`(IN `P_ID` INT)
SELECT 
        u.ID_USUARIO,
        u.NOMBRE_USUARIO,
        u.CONTRASENA,
        u.CORREO_ELECTRONICO,
        u.FECHA_CONEXION_ULTIMA,
        u.COD_PRIMER_INGRESO,
        u.FECHA_VENCIMIENTO,
        u.INTENTOS,
        u.DNI,
        ue.DESCRIPCION AS ESTADO_USUARIO,
        r.DESCRIPCION AS ROL_USUARIO
    FROM 
        TBL_MS_USUARIO u
    INNER JOIN TBL_MS_USUARIO_ESTADO ue ON u.ID_ESTADO_USUARIO = ue.ID_ESTADO_USUARIO
    INNER JOIN TBL_MS_ROL r ON u.ID_ROLL = r.ID_ROL
    WHERE
    	u.COD_PRIMER_INGRESO = P_ID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Update_TBLusuario`(IN `p_ID_USUARIO` INT, IN `p_ID_ESTADO_USUARIO` INT(2), IN `p_ID_ROL` INT(2), IN `p_ID_CENTRO_REGIONAL` INT, IN `p_NOMBRE_USUARIO` VARCHAR(50), IN `p_CONTRASENA` VARCHAR(50), IN `p_DNI` VARCHAR(15), IN `p_CORREO_ELECTRONICO` VARCHAR(50), IN `p_FECHA_CONEXION_ULTIMA` DATE, IN `p_COD_PRIMER_INGRESO` VARCHAR(255), IN `p_FECHA_VENCIMIENTO` DATE, IN `p_INTENTOS` INT)
UPDATE `tbl_ms_usuario`
    SET 
        `ID_ESTADO_USUARIO` = p_ID_ESTADO_USUARIO,
        `ID_ROLL` = p_ID_ROL,
        `ID_CENTRO_REGIONAL` = p_ID_CENTRO_REGIONAL,
        `NOMBRE_USUARIO` = p_NOMBRE_USUARIO,
        `CONTRASENA` = p_CONTRASENA,
        `DNI` = p_DNI,
        `CORREO_ELECTRONICO` = p_CORREO_ELECTRONICO,
        `FECHA_CONEXION_ULTIMA` = p_FECHA_CONEXION_ULTIMA,
        `COD_PRIMER_INGRESO` = p_COD_PRIMER_INGRESO,
        `FECHA_VENCIMIENTO` = p_FECHA_VENCIMIENTO,
        `INTENTOS` = p_INTENTOS
    WHERE `ID_USUARIO` = p_ID_USUARIO$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ProSeguridad_Update_TBLusuario_Verificar`(IN `P_ID` INT, IN `P_CODIGO` VARCHAR(255))
UPDATE `tbl_ms_usuario` SET `ID_ESTADO_USUARIO` = 3, `COD_PRIMER_INGRESO` = P_CODIGO WHERE `tbl_ms_usuario`.`ID_USUARIO` = P_ID$$
DELIMITER ;
