CREATE TABLE TBL_MS_USUARIO (
    ID_USUARIO INT PRIMARY KEY,
    ID_ESTADO_USUARIO INT,
    ID_ROLL INT,
    ID_CENTRO_REGIONAL INT,
    NOMBRE_USUARIO VARCHAR(50),
    CONTRASENA VARCHAR(50),
    CORREO_ELECTRONICO VARCHAR(50),
    FECHA_CONEXION_ULTIMA DATETIME,
    COD_PRIMER_INGRESO VARCHAR(20),
    FECHA_VENCIMIENTO DATETIME
);


CREATE TABLE TBL_MS_USUARIO_ESTADO(
    ID_ESTADO_USUARIO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255)
);
CREATE TABLE TBL_MS_ROL (
    ID_ROL INT PRIMARY KEY,
    CONTRASENA VARCHAR(255)
);

CREATE TABLE TBL_MS_OBJETOS (
    ID_OBJETO INT PRIMARY KEY,
    ID_OBJETO_TIPO INT,
    NOMBRE_OBJETO VARCHAR(50),
    DESCRIPCION VARCHAR(255)
);

CREATE TABLE TBL_MS_OBJETOS_TIPO (
    ID_OBJETO_TIPO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255)
);

CREATE TABLE TBL_MS_PERMISOS (
    ID_PERMISOS INT PRIMARY KEY,
    ID_OBJETO INT,
    ID_ROL INT,
    PERMISO_INSERCION BOOLEAN,
    PERMISO_ELIMINACION BOOLEAN,
    PERMISO_ACTUALIZACION BOOLEAN,
    PERMISO_CONSULTAR BOOLEAN,
    PERMISO_BUSCAR BOOLEAN,
    FECHA_DE_CREACION DATETIME,
    ID_USUARIO_CREADOR INT
);

CREATE TABLE TBL_MS_BITACORA (
    ID_BITACORA INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_OBJETO INT,
    FECHA DATETIME,
    ACCION VARCHAR(255),
    DESCRIPCION VARCHAR(255)
);

CREATE TABLE TBL_MS_HISTORIAL_CONTRASENA (
    ID_HIST_CONTRASENA INT PRIMARY KEY,
    ID_USUARIO INT,
    CONTRASENA VARCHAR(50)
);

CREATE TABLE TBL_MS_PARAMETRO (
    ID_PARAMETRO INT PRIMARY KEY,
    ID_USUARIO INT,
    PARAMETRO VARCHAR(255),
    VALOR VARCHAR(255),
    FECHA_CREACION DATETIME,
    FECHA_MODIFICACION DATETIME
);

-- Agregar FOREIGN KEY usando ALTER TABLE
ALTER TABLE TBL_MS_USUARIO
ADD CONSTRAINT FK_ROL_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO_USUARIO)REFERENCES TBL_MS_USUARIO_ESTADO(ID_ESTADO_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_MS_OBJETOS
ADD CONSTRAINT FK_OBJETO_OBJETO_TIPO FOREIGN KEY (ID_OBJETO_TIPO)   REFERENCES TBL_MS_OBJETOS_TIPO(ID_OBJETO_TIPO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_MS_PERMISOS
ADD CONSTRAINT FK_PERMISOS_OBJETO FOREIGN KEY (ID_OBJETO) REFERENCES TBL_MS_OBJETOS(ID_OBJETO) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_PERMISOS_ROL FOREIGN KEY (ID_ROL) REFERENCES TBL_MS_ROL(ID_ROL) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_MS_BITACORA
ADD CONSTRAINT FK_BITACORA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_BITACORA_OBJETO FOREIGN KEY (ID_OBJETO) REFERENCES TBL_MS_OBJETOS(ID_OBJETO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_MS_HISTORIAL_CONTRASENA
ADD CONSTRAINT FK_HIST_CONTRASENA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_MS_PARAMETRO
ADD CONSTRAINT FK_PARAMETRO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;









CREATE TABLE TBL_SOLVENCIA (
    ID_SOLVENCIA INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_USUARIO_RESPONSABLE INT,
    ESTADO_USUARIO_SOLVENCIA VARCHAR(50),
    FECHA_CREACION DATETIME
);

CREATE TABLE TBL_SOLVENCIA_DETALLE (
    ID_SOLVENCIA_DETALLE INT PRIMARY KEY,
    ID_SOLVENCIA INT,
    ID_PRESTAMO_PENDIENTE INT
);

CREATE TABLE TBL_PRESTAMO (
    ID_PRESTAMO INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_USUARIO_RESPONSABLE INT,
    ID_MATERIAL INT,
    ID_PRESTAMO_TIPO INT,
    ID_PRESTAMO_ESTADO INT,
    CODIGO_VERIFICACION VARCHAR(50),
    FECHA_PRESTAMO DATETIME,
    FECHA_DEVOLUCION DATETIME,
    OBSERVACION TEXT
);

CREATE TABLE TBL_PRESTAMO_ESTADO (
    ID_PRESTAMO_ESTADO INT PRIMARY KEY,
    DESCRIPCION_ESTADO VARCHAR(100)
);

CREATE TABLE TBL_PRESTAMO_TIPO (
    ID_PRESTAMO_TIPO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE TBL_FICHA_INGRESO (
    ID_FICHA_INGRESO INT PRIMARY KEY,
    ID_PROVEEDOR INT,
    ID_COMPRA_TIPO INT,
    ID_MATERIAL INT,
    FECHA_COMPRA DATE
);

CREATE TABLE TBL_PROVEEDOR (
    ID_PROVEEDOR INT PRIMARY KEY,
    NOM_INSTITUCION VARCHAR(150)
);

CREATE TABLE TBL_FICHA_INGRESO_TIPO (
    ID_FICHA_INGRESO_TIPO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE TBL_FICHA_INGRESO_DETALLE (
    ID_FICHA_INGRESO_DETALLE INT PRIMARY KEY,
    ID_FICHA_INGRESO INT,
    ID_MATERIAL INT,
    ID_COMPRA INT,
    CANTIDAD INT
);

CREATE TABLE TBL_PAIS (
    ID_PAIS INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE TBL_DEPARTAMENTO (
    ID_DEPARTAMENTO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE TBL_MUNICIPIO (
    ID_MUNICIPIO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE TBL_LOCACION (
    ID_LOCACION INT PRIMARY KEY,
    ID_PAIS INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE TBL_CENTRO_REGIONAL (
    ID_CENTRO_REGIONAL INT PRIMARY KEY,
    ID_LOCACION INT NOT NULL,
    NOM_CENTRO_REGIONAL VARCHAR(255) NOT NULL
);





ALTER TABLE TBL_SOLVENCIA 
ADD CONSTRAINT FK_SOLVENCIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_SOLVENCIA_DETALLE 
ADD CONSTRAINT FK_SOLVENCIA_DETALLE_SOLVENCIA FOREIGN KEY (ID_SOLVENCIA) REFERENCES TBL_SOLVENCIA(ID_SOLVENCIA) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_PRESTAMO 
ADD CONSTRAINT FK_PRESTAMO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_PRESTAMO_ESTADO FOREIGN KEY (ID_PRESTAMO_ESTADO) REFERENCES TBL_PRESTAMO_ESTADO(ID_PRESTAMO_ESTADO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_FICHA_INGRESO 
ADD CONSTRAINT FK_FICHA_INGRESO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES TBL_PROVEEDOR(ID_PROVEEDOR) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_FICHA_INGRESO_DETALLE 
ADD CONSTRAINT FK_FICHA_INGRESO_DETALLE_FICHA_INGRESO FOREIGN KEY (ID_FICHA_INGRESO) REFERENCES TBL_FICHA_INGRESO(ID_FICHA_INGRESO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_LOCACION 
ADD CONSTRAINT FK_LOCACION_PAIS FOREIGN KEY (ID_PAIS) REFERENCES TBL_PAIS(ID_PAIS) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_LOCACION_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES TBL_DEPARTAMENTO(ID_DEPARTAMENTO) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_LOCACION_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES TBL_MUNICIPIO(ID_MUNICIPIO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TBL_CENTRO_REGIONAL 
ADD CONSTRAINT FK_CENTRO_REGIONAL_LOCACION FOREIGN KEY (ID_LOCACION) REFERENCES TBL_LOCACION(ID_LOCACION) ON DELETE CASCADE ON UPDATE CASCADE;
