CREATE TABLE TBL_MS_USUARIO (
    ID_USUARIO INT PRIMARY KEY,
    ID_ESTADO_USUARIO INT,
    ID_ROLL INT,
    ID_CENTRO_REGIONAL INT,
    NOMBRE_USUARIO VARCHAR(50),
    CONTRASENA VARCHAR(50),
    CORREO_ELECTRONICO VARCHAR(50),
    FECHA_CONEXION_ULTIMA DATETIME,
    COD_PRIMER_INGRESO VARCHAR(20),
    FECHA_VENCIMIENTO DATETIME
);
CREATE TABLE TBL_MS_ROL (
    ID_ROL INT PRIMARY KEY
    CONTRASENA VARCHAR(255)
);

CREATE TABLE TBL_MS_OBJETOS (
    ID_OBJETO INT PRIMARY KEY,
    ID_OBJETO_TIPO INT,
    NOMBRE_OBJETO VARCHAR(50),
    DESCRIPCION VARCHAR(255)
);

-- Creación de la tabla TBL_MS_OBJETOS_TIPO
CREATE TABLE TBL_MS_OBJETOS_TIPO (
    ID_OBJETO_TIPO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255)
);

-- Creación de la tabla TBL_MS_PERMISOS
CREATE TABLE TBL_MS_PERMISOS (
    ID_PERMISOS INT PRIMARY KEY,
    ID_OBJETO INT,
    ID_ROL INT,
    PERMISO_INSERCION BOOLEAN,
    PERMISO_ELIMINACION BOOLEAN,
    PERMISO_ACTUALIZACION BOOLEAN,
    PERMISO_CONSULTAR BOOLEAN,
    PERMISO_BUSCAR BOOLEAN,
    FECHA_DE_CREACION DATETIME,
    ID_USUARIO_CREADOR INT
);

-- Creación de la tabla TBL_MS_BITACORA
CREATE TABLE TBL_MS_BITACORA (
    ID_BITACORA INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_OBJETO INT,
    FECHA DATETIME,
    ACCION VARCHAR(255),
    DESCRIPCION VARCHAR(255)
);

-- Creación de la tabla TBL_MS_HISTORIAL_CONTRASENA
CREATE TABLE TBL_MS_HISTORIAL_CONTRASENA (
    ID_HIST_CONTRASENA INT PRIMARY KEY,
    ID_USUARIO INT,
    CONTRASENA VARCHAR(50)
);

-- Creación de la tabla TBL_MS_PARAMETRO
CREATE TABLE TBL_MS_PARAMETRO (
    ID_PARAMETRO INT PRIMARY KEY,
    ID_USUARIO INT,
    PARAMETRO VARCHAR(255),
    VALOR VARCHAR(255),
    FECHA_CREACION DATETIME,
    FECHA_MODIFICACION DATETIME
);

-- Agregar FOREIGN KEY usando ALTER TABLE
ALTER TABLE TBL_MS_ROL
ADD CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO);

ALTER TABLE TBL_MS_OBJETOS
ADD CONSTRAINT FK_OBJETO_OBJETO_TIPO FOREIGN KEY (ID_OBJETO_TIPO) REFERENCES TBL_MS_OBJETOS_TIPO(ID_OBJETO_TIPO);

ALTER TABLE TBL_MS_PERMISOS
ADD CONSTRAINT FK_PERMISOS_OBJETO FOREIGN KEY (ID_OBJETO) REFERENCES TBL_MS_OBJETOS(ID_OBJETO),
ADD CONSTRAINT FK_PERMISOS_ROL FOREIGN KEY (ID_ROL) REFERENCES TBL_MS_ROL(ID_ROL);

ALTER TABLE TBL_MS_BITACORA
ADD CONSTRAINT FK_BITACORA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO),
ADD CONSTRAINT FK_BITACORA_OBJETO FOREIGN KEY (ID_OBJETO) REFERENCES TBL_MS_OBJETOS(ID_OBJETO);

ALTER TABLE TBL_MS_HISTORIAL_CONTRASENA
ADD CONSTRAINT FK_HIST_CONTRASENA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO);

ALTER TABLE TBL_MS_PARAMETRO
ADD CONSTRAINT FK_PARAMETRO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_MS_USUARIO(ID_USUARIO);
